version: "3.7"

services:

  runner-1:
    container_name: runner-1
    image: ghcr.io/gamify-it/actions-runner:latest
    restart: always
    environment:
      - url=${url}
      - token=${token1}
      - name=${name1}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  runner-2:
    container_name: runner-2
    image: ghcr.io/gamify-it/actions-runner:latest
    restart: always
    environment:
      - url=${url}
      - token=${token2}
      - name=${name2}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  runner-3:
    container_name: runner-3
    image: ghcr.io/gamify-it/actions-runner:latest
    restart: always
    environment:
      - url=${url}
      - token=${token3}
      - name=${name3}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  runner-4:
    container_name: runner-4
    image: ghcr.io/gamify-it/actions-runner:latest
    restart: always
    environment:
      - url=${url}
      - token=${token4}
      - name=${name4}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock