version: "3.7"

services:

  runner-1:
    container_name: runner-1
    image: ghcr.io/gamify-it/actions-runner:latest
    restart: always
    privileged: true
    environment:
      - url=${url}
      - token=${token}
      - name=${name1}

  runner-2:
    container_name: runner-2
    image: ghcr.io/gamify-it/actions-runner:latest
    restart: always
    privileged: true
    environment:
      - url=${url}
      - token=${token}
      - name=${name2}

  runner-3:
    container_name: runner-3
    image: ghcr.io/gamify-it/actions-runner:latest
    restart: always
    privileged: true
    environment:
      - url=${url}
      - token=${token}
      - name=${name3}

  runner-4:
    container_name: runner-4
    image: ghcr.io/gamify-it/actions-runner:latest
    restart: always
    privileged: true
    environment:
      - url=${url}
      - token=${token}
      - name=${name4}