version: "3.7"

services:

  runner-1:
    container_name: runner-1
    image: ghcr.io/gamify-it/actions-runner:latest
    restart: always
    privileged: true
    environment:
      - url=${url}
      - token=${token}
      - name=${name1}
      - workdir=/actionsRunnerWorkdir/${name1}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /actionsRunnerWorkdir/${name1}:/actionsRunnerWorkdir/${name1}

  runner-2:
    container_name: runner-2
    image: ghcr.io/gamify-it/actions-runner:latest
    restart: always
    privileged: true
    environment:
      - url=${url}
      - token=${token}
      - name=${name2}
      - workdir=/actionsRunnerWorkdir/${name2}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /actionsRunnerWorkdir/${name2}:/actionsRunnerWorkdir/${name2}

  runner-3:
    container_name: runner-3
    image: ghcr.io/gamify-it/actions-runner:latest
    restart: always
    privileged: true
    environment:
      - url=${url}
      - token=${token}
      - name=${name3}
      - workdir=/actionsRunnerWorkdir/${name3}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /actionsRunnerWorkdir/${name3}:/actionsRunnerWorkdir/${name3}

  runner-4:
    container_name: runner-4
    image: ghcr.io/gamify-it/actions-runner:latest
    restart: always
    privileged: true
    environment:
      - url=${url}
      - token=${token}
      - name=${name4}
      - workdir=/actionsRunnerWorkdir/${name4}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /actionsRunnerWorkdir/${name4}:/actionsRunnerWorkdir/${name4}