version: "3.7"

services:

  runner-1:
    container_name: ${name1}
    build: .
    restart: always
    environment:
      - url=${url}
      - token=${token}
      - name=${name}
      - workdir=/actionsRunnerWorkdir/${name}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /actionsRunnerWorkdir/${name}:/actionsRunnerWorkdir/${name}